ARG NODE_VERSION=16
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/server/dist/ && yarn build --scope=server

COPY ./packages/client/dist /app/client
COPY ./packages/client/dist-ssr /app/client

EXPOSE $SERVER_PORT
CMD [ "node", "/app/packages/server/dist/index.js" ]
