name: YCloud CI

on:
  push:
    branches: ['features/COD-73-github-action']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: crpn9mnggobsk72cbsih
          CR_REPO: matchthree
          IMAGE_TAG: ${{ github.sha }}
        run: docker-compose -f "docker-compose.yml" up -d --build
